name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build-and-attach:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip build wheel

      - name: Build sdist & wheel
        run: |
          python -m build
          ls -l dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcgt-dist
          path: dist/*

      - name: Create GitHub Release (if not exists) & attach assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
