name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: ✨ Features
    labels: [feat, feature, enhancement]
  - title: 🐛 Fixes
    labels: [fix, bug]
  - title: 🧰 Maintenance
    labels: [chore, ci, deps, refactor]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
template: |
  ## Changements
  $CHANGES
