name: mcgt
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip

  # Core scientific stack (laisser le solver choisir les builds compatibles)
  - numpy
  - pandas
  - scipy
  - matplotlib
  - h5py
  - pyyaml
  - jsonschema
  - tqdm
  - click
  - rich
  - requests
  - python-dateutil
  - packaging
  - sympy
  - ipykernel
  - jupyterlab
  - pytest

  # Optional compiled/acceleration (décommenter si besoin)
  - numba
  - llvmlite

  # CAMB / LALSuite: fortement recommandé via conda-forge (si nécessaire,
  # décommenter ci-dessous OU installer séparément dans un env dédié).
  # - camb
  # - lalsuite

  - pip:
    - -e .
