name: Feature
description: Proposer une amélioration
labels: [enhancement]
body:
  - type: textarea
    id: value
    attributes: { label: "Valeur", description: "Pourquoi c'est utile ?" }
    validations: { required: true }
  - type: textarea
    id: scope
    attributes: { label: "Portée", description: "Critères d'acceptation" }
