models:
  default:
    Omega_m: [0.10, 0.50]
    H_0: [60.0, 80.0]
    w_0: [-2.5, -0.3]
    w_a: [-3.0, 3.0]
    S_8: [0.60, 1.00]
  tide:
    Omega_m: [0.10, 0.50]
    H_0: [60.0, 80.0]
    kappa: [0.0, 200.0]
    S_8: [0.60, 1.00]
