name: CI
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python -m pip install --upgrade pip
      - run: pip install pre-commit jsonschema pandas ruff
      - name: Pre-commit (strict au niveau Phase 0 allégé)
        run: |
          pre-commit run --all-files || (git status --porcelain && git --no-pager diff && exit 1)
      - name: Validate JSON (optionnel)
        run: |
          if [ -x zz-schemas/validate_all.sh ]; then ./zz-schemas/validate_all.sh || true; fi
