name: ci-fig-manifest
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "zz-manifests/figure_manifest.csv"
      - "zz-figures/**"
      - "zz-scripts/**"
      - ".github/workflows/ci-fig-manifest.yml"
      - "tools/check_fig_manifest.sh"
      - "tools/_check_fig_manifest.py"
  push:
    branches: ["**"]
    paths:
      - "zz-manifests/figure_manifest.csv"
      - "zz-figures/**"
      - "zz-scripts/**"
      - ".github/workflows/ci-fig-manifest.yml"
      - "tools/check_fig_manifest.sh"
      - "tools/_check_fig_manifest.py"
jobs:
  verify-figures:
    runs-on: ubuntu-latest
    strategy:
      matrix: { python-version: ["3.10", "3.11", "3.12"] }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "${{ matrix.python-version }}" }
      - name: Check figure manifest (hash/existence)
        run: tools/check_fig_manifest.sh
