# added by policies_guard_common_fixes
permissions:
  contents: read
name: ci-yaml-check
on:
concurrency:
  group: .github/workflows/ci-yaml-check.yml-${{ github.ref }}
  cancel-in-progress: true
  push: {}
  pull_request: {}

jobs:
  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PyYAML
        run: python -m pip install --upgrade pip pyyaml
      - name: Validate workflow YAMLs
        run: bash tools/yaml_check.sh
