name: figures-guard

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run guard
        run: |
          bash tools/ci_step2_figures_guard.sh
