name: figures-guard

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Figures guard (manifest/drift/duplicates)
        run: bash tools/ci_step2_figures_guard.sh
      - name: Figures index guard (CSV consistency)
        env:
          MCGT_NO_SHELL_DROP: "1"
        run: bash tools/check_figures_index.sh
