# added by policies_guard_common_fixes
permissions:
  contents: read
name: Manifest drift check
on:
  workflow_dispatch:
concurrency:
  group: .github/workflows/manifest-drift.yml-${{ github.ref }}
  cancel-in-progress: true
  pull_request:
  push:
    branches: [ main ]
jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps (pytest only for scripts that import it)
        run: python -m pip install --upgrade pip pytest -c constraints/security-pins.txt
      - name: Dry-run manifest refresh (fail on drift)
        shell: bash
        run: |
          set -euo pipefail
          cp zz-manifests/manifest_master.json /tmp/manifest_before.json
          KEEP_OPEN=0 bash tools/refresh_master_manifest_full.sh
          if ! diff -q /tmp/manifest_before.json zz-manifests/manifest_master.json >/dev/null; then
            echo "::error::manifest drift detected. Run tools/refresh_master_manifest_full.sh locally and commit."
            # Restore to avoid dirty workspace in CI
            cp /tmp/manifest_before.json zz-manifests/manifest_master.json
            exit 1
          fi
          echo "No drift."
