name: manifests-guard
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate figures sha256 manifest
        run: bash tools/ci_step3_validate_manifests.sh
