name: Build & Publish to TestPyPI (isolated)

on:
  workflow_dispatch: {}
  push:
    tags:
      - v*-testretry.**

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade build tooling
        run: |
          python -m pip install -U pip build wheel

      - name: Clean
        run: rm -rf dist/ build/ *.egg-info || true

      - name: Build sdist & wheel
        run: python -m build

      - name: Twine check (local)
        run: |
          python -m pip install -U twine
          python -m twine check dist/*

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-testpypi:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install twine
        run: python -m pip install -U pip twine

      - name: Twine check (artifact)
        run: python -m twine check dist/*

      # IMPORTANT: uniquement des inputs en kebab-case.
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist
          verify-metadata: true
          skip-existing: true
          attestations: false
