name: .github/workflows/publish_testonly.yml

on:
  workflow_dispatch:
  push:
    branches:
      - ci/testpypi-workflow-rmid
    paths:
      - .ci_poke/**
      - .github/workflows/publish_testonly.yml
      - pyproject.toml
      - setup.cfg
      - setup.py
      - src/**
      - MCGT/**
      - requirements*.txt
      - poetry.lock
      - package.json

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build dist (wheel+sdist)
        run: |
          python -m build
          ls -la dist || true

      - name: Upload artifact 'dist'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 7

  publish-testpypi:
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/ci/testpypi-workflow-rmid' && secrets.TEST_PYPI_API_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact 'dist'
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          packages-dir: dist
          skip-existing: true
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
