name: pypi-build
name: pypi-build
true:
  workflow_dispatch: null
  push:
    branches:
    - '**'
  pull_request:
    branches:
    - '**'
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
    - name: Build sdist/wheel
      run: 'python -m pip install -U pip build twine -c constraints/security-pins.txt

        python -m build

        python -m twine check dist/*

        '
    - name: Upload dist artifacts
      uses: actions/upload-artifact@v4
      with:
        name: py-dist
        path: dist/*
    name: build
'on':
  pull_request: {}
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
