name: pypi-build

on:
  push:
    branches: [ main, 'cleanup/**' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          python-version: '3.12'
      - name: Sanity echo
        run: python -V && echo "pypi-build alive"
          cache: pip

      - name: Build sdist/wheel
        run: |
          python -m pip install -U pip build twine -c constraints/security-pins.txt
          python -m build
          python -m twine check dist/*
