# added by policies_guard_common_fixes
permissions:
  contents: read
name: quality-guards
on: [push, pull_request]
concurrency:
  group: .github/workflows/quality-guards.yml-${{ github.ref }}
  cancel-in-progress: true
jobs:
  perms-and-shebang:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'push' || !startsWith(github.ref, 'refs/heads/rewrite/') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Non-shebang executables
        run: |
          set -euo pipefail
          bad=0
          while IFS= read -r -d '' f; do
            head -n1 "$f" | grep -q '^#!' || { echo "❌ Exécutable sans shebang: $f"; bad=1; }
          done < <(find . -path ./.git -prune -o -type f -perm -111 -print0)
          [ "$bad" -eq 0 ] && echo "✅ OK: tous les exécutables ont un shebang" || exit 1
      - name: Assets avec bit exécutable (interdit)
        run: |
          set -euo pipefail
          exts=(png jpg jpeg gif svg tex txt md rst csv tsv json yml yaml ini toml bib ipynb dat)
          bad=0
          for e in "${exts[@]}"; do
            while IFS= read -r -d '' f; do
              if [ -x "$f" ]; then echo "❌ Bit +x sur asset: $f"; bad=1; fi
            done < <(git ls-files -z "*.${e}")
          done
          [ "$bad" -eq 0 ] && echo "✅ OK: aucun asset n’a le bit exécutable" || exit 1
