name: publish to PyPI
on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write   # OIDC → Trusted Publishing

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build sdist & wheel (+ post-fixers) & checks
        run: |
          python -m pip install --upgrade pip build twine
          rm -rf dist build *.egg-info
          python -m build
          # Post-build fixers (idempotents)
          if [ -f tools/repair_wheel_metadata.py ]; then python tools/repair_wheel_metadata.py dist/*.whl || true; fi
          if [ -f tools/repair_sdist_metadata.py ]; then python tools/repair_sdist_metadata.py dist/*.tar.gz || true; fi
          twine check dist/*

      - name: Publish to PyPI via OIDC (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
