# added by policies_guard_common_fixes
permissions:
  contents: read
name: release-assets
on:
  workflow_dispatch:
concurrency:
  group: .github/workflows/release-assets.yml-${{ github.ref }}
  cancel-in-progress: true
  push:
    tags:
      - "v*.*.*"
jobs:
  attach-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build PDF (main.tex)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: false
          texlive_version: 2023
      - name: Créer/mettre à jour la release et attacher main.pdf
        uses: softprops/action-gh-release@v2
        with:
          files: |
            main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
