name: publish to PyPI
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write   # OIDC -> Trusted Publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build sdist & wheel (+ post-fixers) & checks
        run: |
          python -m pip install --upgrade pip build twine
          rm -rf dist build *.egg-info
          python -m build
          python tools/repair_wheel_metadata.py dist/*.whl || true
          python tools/repair_sdist_metadata.py dist/*.tar.gz || true
          twine check dist/*

      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          skip-existing: true
