name: Publish
on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-rc*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Build
        run: |
          python -m pip install -U pip build
          python -m build
      - name: Twine Check
        run: |
          python -m pip install -U twine
          python -m twine check dist/*
      - name: Publish (TestPyPI for -rc tags)
        if: contains(github.ref, '-rc')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_API_TOKEN }}
        run: |
          python -m twine upload --non-interactive --repository-url https://test.pypi.org/legacy/ dist/*
      - name: Publish (PyPI for final tags)
        if: ${{ !contains(github.ref, '-rc') }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m twine upload --non-interactive dist/*
