name: sanity-main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  diag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build diag payload
        shell: bash
        run: |
          set -euo pipefail
          OUT=".ci-out/sanity-diag"
          mkdir -p "$OUT"
          TS="$(date -u +%FT%TZ)"

          # Écriture du JSON sans here-doc (robuste aux collages)
          printf '{\n'                          >  "$OUT/diag.json"
          printf '  "timestamp": "%s",\n' "$TS" >> "$OUT/diag.json"
          printf '  "errors": 0,\n'             >> "$OUT/diag.json"
          printf '  "warnings": 0,\n'           >> "$OUT/diag.json"
          printf '  "issues": [\n'              >> "$OUT/diag.json"
          printf '    { "severity": "INFO", "code": "PING", "msg": "sanity OK" }\n' >> "$OUT/diag.json"
          printf '  ]\n'                        >> "$OUT/diag.json"
          printf '}\n'                          >> "$OUT/diag.json"

          # Petit mémo texte
          printf "timestamp=%s\nok=true\n" "$TS" > "$OUT/diag.txt"

          # Résumé dans l'onglet "Summary" du job (fallback vers fichier local)
          SUM="${GITHUB_STEP_SUMMARY:-$OUT/SUMMARY.md}"
          {
            echo "### Sanity Diag"
            echo
            cat "$OUT/diag.json"
            echo
            echo "Fichiers :"
            ls -1 "$OUT" || true
          } >> "$SUM"

      - name: Upload artifact (sanity-diag)
        uses: actions/upload-artifact@v4
        with:
          name: sanity-diag
          path: .ci-out/sanity-diag/**
          if-no-files-found: error
          retention-days: 5
