name: sanity-dispatch
on:
  workflow_dispatch: {}
  push:
    branches: ['*']
  pull_request: {}

jobs:
  sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Hello (smoke test)
        run: echo "sanity-dispatch OK @ 20251001T110812"
