name: "sanity"
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}  # CAT v14 @ 20251001T115209
  repository_dispatch:
    types: [sanity]

jobs:
  sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: "Install deps (best-effort)"
        shell: bash
        run: |
          python -m pip install -U pip || true
          [ -f requirements-lock.txt ] && python -m pip install -r requirements-lock.txt || true
          [ -f requirements-dev.txt ] && python -m pip install -r requirements-dev.txt || true

      - name: "Guard: no .RECIPEPREFIX"
        shell: bash
        run: bash tools/guard_no_recipeprefix.sh || echo "guard: skipped/failed (non-fatal)"

      - name: "Tests (skip if none)"
        shell: bash
        run: |
          if [ -d tests ] && ls tests 2>/dev/null | head -n1 >/dev/null; then
            python -m pytest -q || echo "pytest a échoué (non-bloquant)"
          else
            echo "Aucun tests/ détecté : skip"
          fi

      - name: "Sanity diag"
        shell: bash
        run: bash tools/sanity_diag.sh

      - name: "Upload diag artifact"
        uses: actions/upload-artifact@v4
        with:
          name: sanity-diag
          path: .ci-out/
          if-no-files-found: ignore
