name: sanity
on:
  push:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps (minimal)
        run: |
          python -m pip install -U pip
          if [ -f requirements-lock.txt ]; then python -m pip install -r requirements-lock.txt || true; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt || true; fi

      - name: "Guard: no .RECIPEPREFIX"
        run: bash tools/guard_no_recipeprefix.sh

      - name: Dry-run Make (fix-manifest)
        run: make -n fix-manifest

      - name: Manifests strict diag
        run: |
          python zz-manifests/diag_consistency.py zz-manifests/manifest_master.json \
            --report json --normalize-paths --apply-aliases --strip-internal \
            --content-check --fail-on errors

      - name: Pytest
        run: python -m pytest -q
