name: "sanity-main"
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: "Install deps (best-effort)"
        shell: bash
        continue-on-error: true
        run: |
          python -m pip install -U pip || true
          [ -f requirements-lock.txt ] && python -m pip install -r requirements-lock.txt || true
          [ -f requirements-dev.txt ] && python -m pip install -r requirements-dev.txt || true

      - name: "Guard: no .RECIPEPREFIX"
        shell: bash
        continue-on-error: true
        run: bash tools/guard_no_recipeprefix.sh

      - name: "Tests (skip si absents)"
        shell: bash
        continue-on-error: true
        run: |
          if [ -d tests ] && ls tests 2>/dev/null | head -n1 >/dev/null; then
            python -m pytest -q || echo "pytest a échoué (non-bloquant)"
          else
            echo "Aucun tests/ détecté : skip"
          fi

      - name: "Sanity diag (always)"
        if: ${{ always() }}
        shell: bash
        continue-on-error: false
        run: bash tools/sanity_diag.sh

      - name: "Upload diag artifact (always)"
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: sanity-diag
          path: .ci-out/
          if-no-files-found: error
