name: sanity-main
run-name: sanity-main • ${{ github.event_name }} • ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.ci-logs/**'
      - '.ci-archive/**'
  schedule:
    - cron: '0 6 * * *' # tous les jours 06:00 UTC

concurrency:
  group: sanity-main-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  diag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build diag payload
        shell: bash
        run: |
          set -euo pipefail
          OUT=".ci-out/sanity-diag"
          mkdir -p "$OUT"
          TS="$(date -u +%FT%TZ)"
          {
            printf '{\n'
            printf '  "timestamp": "%s",\n' "$TS"
            printf '  "errors": 0,\n'
            printf '  "warnings": 0,\n'
            printf '  "issues": [\n'
            printf '    { "severity": "INFO", "code": "PING", "msg": "sanity OK" }\n'
            printf '  ]\n'
            printf '}\n'
          } > "$OUT/diag.json"
          {
            echo "Sanity diag — $TS"
            echo
            echo "- errors: 0"
            echo "- warnings: 0"
            echo "- issues:"
            echo "  - [INFO] PING: sanity OK"
          } > "$OUT/diag.txt"

      - name: Upload artifact (sanity-diag)
        uses: actions/upload-artifact@v4
        with:
          name: sanity-diag
          path: .ci-out/sanity-diag/
          if-no-files-found: error
          retention-days: 7

      - name: Job summary (Markdown)
        if: always()
        shell: bash
        run: |
          {
            echo "## Sanity diag"
            echo
            echo "- Timestamp: $(command -v jq >/dev/null 2>&1 && jq -r .timestamp .ci-out/sanity-diag/diag.json || date -u +%FT%TZ)"
            echo "- Errors: $(command -v jq >/dev/null 2>&1 && jq -r .errors .ci-out/sanity-diag/diag.json || echo 0)"
            echo "- Warnings: $(command -v jq >/dev/null 2>&1 && jq -r .warnings .ci-out/sanity-diag/diag.json || echo 0)"
            echo
            echo "### Issues"
            if command -v jq >/dev/null 2>&1; then
              jq -r '.issues[] | "- [" + .severity + "] " + .code + ": " + .msg' .ci-out/sanity-diag/diag.json || true
            else
              cat .ci-out/sanity-diag/diag.txt || true
            fi
          } >> "$GITHUB_STEP_SUMMARY"

  meta:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install actionlint (pinned)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .tools/bin
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash \
            | bash -s -- -b .tools/bin v1.7.1
          echo "$PWD/.tools/bin" >> "$GITHUB_PATH"

      - name: Run actionlint
        shell: bash
        continue-on-error: true
        run: |
          set -euo pipefail
          .tools/bin/actionlint -color -shellcheck= -format '{{.File}}:{{.Line}}:{{.Col}}: {{.Message}}'

      - name: Run shellcheck (tools/*.sh)
        shell: bash
        continue-on-error: true
        run: |
          set -euo pipefail
          if command -v shellcheck >/dev/null 2>&1; then
            shopt -s nullglob
            FILES=(tools/*.sh)
            if (( ${#FILES[@]} )); then
              shellcheck -S style -x "${FILES[@]}" || true
            else
              echo "No shell scripts under tools/"
            fi
          else
            echo "shellcheck not found on runner (unexpected on ubuntu-latest), skipping"
          fi

      - name: Meta summary
        if: always()
        shell: bash
        run: |
          echo "## Meta checks" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "- actionlint: executed (pinned v1.7.1)" >> "$GITHUB_STEP_SUMMARY"
          echo "- shellcheck: executed on tools/*.sh (if any)" >> "$GITHUB_STEP_SUMMARY"
