name: sanity-main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  diag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build diag payload
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .ci-out/sanity-diag
          TS="$(date -u +%FT%TZ)"

          cat > .ci-out/sanity-diag/diag.json <<'JSON'
          {
            "timestamp": "__TS__",
            "errors": 0,
            "warnings": 0,
            "issues": [
              { "severity": "INFO", "code": "PING", "msg": "sanity OK" }
            ]
          }
          JSON

          sed -i "s/__TS__/${TS}/" .ci-out/sanity-diag/diag.json
          printf "timestamp=%s\nok=true\n" "${TS}" > .ci-out/sanity-diag/diag.txt

      - name: Pack artifact + summary (robuste)
        shell: bash
        run: |
          set -euo pipefail
          test -s .ci-out/sanity-diag/diag.json
          test -s .ci-out/sanity-diag/diag.txt

          tar czf .ci-out/sanity-diag/sanity-diag.tgz -C .ci-out sanity-diag

          SUM="${GITHUB_STEP_SUMMARY:-.ci-out/sanity-diag/SUMMARY.md}"
          {
            echo "### Sanity Diag"
            echo
            cat .ci-out/sanity-diag/diag.json
            echo
            echo 'Packaged files:'
            find .ci-out/sanity-diag -maxdepth 1 -type f -printf ' - %f\n'
          } >> "$SUM"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sanity-diag
          path: .ci-out/sanity-diag/sanity-diag.tgz
          if-no-files-found: error
          retention-days: 5
