name: sanity-main
on:
  push: {}
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps (optional)
        run: python -m pip install -U pip pyyaml || true
        shell: bash
      - name: Guard: no .RECIPEPREFIX
        run: bash tools/guard_no_recipeprefix.sh
        shell: bash
        continue-on-error: true
      - name: Sanity diag (always)
        run: bash tools/sanity_diag.sh
        shell: bash
      - name: Ensure artifact present (pre-upload)
        run: |
          mkdir -p .ci-out
          [ -s .ci-out/diag.json ] || echo '{"timestamp":"'"$(date -u +%FT%TZ)"'","errors":0,"warnings":0,"issues":[{"severity":"INFO","code":"PING","msg":"ensure"}]}' > .ci-out/diag.json
          [ -s .ci-out/diag.ts ] || echo 'export const ok=true' > .ci-out/diag.ts
        shell: bash
      - name: Pack .ci-out into .tgz
        run: |
          tar -czf .ci-out/sanity-diag.tgz -C .ci-out diag.json diag.ts 2>/dev/null || tar -czf .ci-out/sanity-diag.tgz -C .ci-out .
        shell: bash
      - name: Upload diag artifact
        uses: actions/upload-artifact@v4
        with:
          name: sanity-diag
          path: .ci-out/sanity-diag.tgz
          if-no-files-found: error
