name: sanity-main

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build diag payload
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .ci-out/sanity-diag
          TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

          cat > .ci-out/sanity-diag/diag.json <<'JSON'
          {
            "timestamp": "__TS__",
            "errors": 0,
            "warnings": 0,
            "issues": [
              { "severity": "INFO", "code": "PING", "msg": "sanity OK" }
            ]
          }
          JSON
          sed -i "s/__TS__/${TS}/" .ci-out/sanity-diag/diag.json

          cat > .ci-out/sanity-diag/diag.ts <<'TS'
          export const timestamp = "__TS__";
          export const ok = true;
          TS
          sed -i "s/__TS__/${TS}/" .ci-out/sanity-diag/diag.ts

      - name: Pack artifact
        shell: bash
        run: |
          set -euo pipefail
          tar czf .ci-out/sanity-diag/sanity-diag.tgz -C .ci-out sanity-diag
          echo '### Sanity Diag' >> "$GITHUB_STEP_SUMMARY"
          cat .ci-out/sanity-diag/diag.json >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sanity-diag
          path: .ci-out/sanity-diag/sanity-diag.tgz
          if-no-files-found: error
