name: sanity-main
run-name: sanity-main • ${{ github.event_name }} • ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - '.ci-logs/**'
      - '.ci-archive/**'
  schedule:
    - cron: '0 6 * * *' # Tous les jours à 06:00 UTC

concurrency:
  group: sanity-main-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  diag:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build diag payload
        shell: bash
        run: |
          set -euo pipefail
          OUT=".ci-out/sanity-diag"
          mkdir -p "$OUT"
          TS="$(date -u +%FT%TZ)"
          {
            printf '{\n'
            printf '  "timestamp": "%s",\n' "$TS"
            printf '  "errors": 0,\n'
            printf '  "warnings": 0,\n'
            printf '  "issues": [\n'
            printf '    { "severity": "INFO", "code": "PING", "msg": "sanity OK" }\n'
            printf '  ]\n'
            printf '}\n'
          } > "$OUT/diag.json"
          printf "timestamp=%s\nok=true\n" "$TS" > "$OUT/diag.txt"
          SUM="${GITHUB_STEP_SUMMARY:-$OUT/SUMMARY.md}"
          {
            echo "### Sanity Diag"
            echo
            cat "$OUT/diag.json"
            echo
            echo "Fichiers :"
            ls -1 "$OUT" || true
          } >> "$SUM"

      - name: Upload artifact (sanity-diag)
        uses: actions/upload-artifact@v4
        with:
          name: sanity-diag
          path: .ci-out/sanity-diag/**
          if-no-files-found: error
          retention-days: 5
