name: secret-scan
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }
concurrency:
  group: secrets-${{ github.ref }}
  cancel-in-progress: true
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: detect --source . --no-banner --config .gitleaks.toml --redact
