# added by policies_guard_common_fixes
permissions:
  contents: read
name: secret-scan

on:
  workflow_dispatch:
  push:
    branches: ['**']        # pas de restriction
  pull_request:              # pas de paths:/types:/branches: sous pull_request
    branches: ['**']

concurrency:
  group: secrets-${{ github.ref }}
  cancel-in-progress: false   # ⚠️ important: false pour éviter les "cancelled"

jobs:
  gitleaks:                   # ⚠️ le job s'appelle exactement gitleaks (sans matrix suffix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Pas d'if: restrictif ici ni sur les steps ci-dessous
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --source . --redact --report-format sarif --report-path gitleaks.sarif
      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
