- name: Gitleaks scan (action v2)
  uses: gitleaks/gitleaks-action@v2
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# L’action écrit par défaut 'results.sarif' → on renomme en 'gitleaks.sarif'
- name: Normalize SARIF filename
  if: always()
  run: |
    if [ -f results.sarif ]; then mv results.sarif gitleaks.sarif; fi
    # bonus : trace lisible si rien n’a été produit
    ls -l || true

# Upload vers Code Scanning
- name: Upload SARIF
  uses: github/codeql-action/upload-sarif@v3
  with:
    sarif_file: gitleaks.sarif
    category: gitleaks
    checkout_path: ${{ github.workspace }}
    wait-for-processing: true

# Upload brut des artefacts (inclure le bon nom)
- name: Upload raw logs/artifacts
  uses: actions/upload-artifact@v4
  with:
    name: gitleaks-logs-${{ github.run_id }}
    path: |
      gitleaks.sarif
      **/gitleaks*.log
      **/*gitleaks*.txt
      **/report*.json
      **/report*.txt
    if-no-files-found: warn
