# FICHIER: _tmp/mcgt/patches/secret-scan.verbose.yml
# EMPLACEMENT: /home/<USER>/MCGT/_tmp/mcgt/patches/secret-scan.verbose.yml
# RÔLE: Workflow Gitleaks verbeux, stable et traçable (artifacts + SARIF). Ne modifie pas le code.
name: secret-scan

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

concurrency:
  group: secret-scan-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for leak scan)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks scan (action v2)
        id: gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner -v --redact --exit-code 1

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
          category: gitleaks

      - name: Upload raw logs/artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-logs-${{ github.run_id }}
          path: |
            gitleaks.sarif
            **/gitleaks*.log
            **/*gitleaks*.txt
            **/report*.json
            **/report*.txt

    # IMPORTANT: ce nom de job doit rester "gitleaks" pour matcher le context requis "secret-scan/gitleaks"
