permissions:
  contents: read
name: secret-scan

on:
  workflow_dispatch:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

concurrency:
  group: secrets-${{ github.ref }}
  cancel-in-progress: false

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner --source . --redact --report-format sarif --report-path gitleaks.sarif

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
